#+STARTUP: overview

Other variants. If source not mentioned, it's
https://tobylobster.github.io/rom_library/

* DFS 2.45

** DFS 2.45 rev 1191

* DFS 2.42

** Acorn DFS v2.42 + View vB3.0.rom

The DFS part is identical to variant 1.

** Acorn DFS v2.42 [variant 2] [Mertec Companion v0.99].rom

The DFS part is identical to variant 1.

** Acorn DFS v2.42 [variant 1]

This is the one supplied on the PC 128 S welcome disk.

* DFS 2.29

** Acorn DFS v2.29 [variant 6] + Mouse v1.00 

Same as variant 5 but a tiny bit of extra junk at the end. Looks like
valid code, but it pushes the size over 16K. Variant 5 might be bad?

** Acorn DFS v2.29 [variant 5]

As variant 1, but with a mouse ROM included.

** Acorn DFS v2.29 [variant 4]

As variant 2, but SRAM has been stripped out.

** Acorn DFS v2.29 [variant 3]

Bad - DFS is 16KB but this is 8 KB.

** Acorn DFS v2.29 [variant 2]

As variant 1, but patches this line:

: 2785	.8cab	5d 60 91	eor $9160,x	                eor L90D1,x     ;apply latches for drive 0..3 in X

To jump to a little routine that does ASL A:ASL A first. This appears
to be a version of the double density fix mentioned here:
http://www.adsb.co.uk/bbc/dfs.html

** Acorn DFS v2.29 [variant 1]

This is the one supplied on the Master 128 welcome disk.

Includes SRAM 1.06.

* DFS 2.28

** Acorn DFS v2.28

Looks quite different from DFS 2.29.

Includes SRAM 1.06.

Doesn't include Tube, so presumably intended for use on Master.
